export const creatureRaces = [
    'Alien', 'Ape', 'Azra', 'Centaur', 'Cyclops', 'Dauthi', 'Dryad', 'Dwarf', 'Elf',
    'Faerie', 'Giant', 'Gnome', 'Goblin', 'Gorgon', 'Hag', 'Halfling', 'Human', 'Kithkin',
    'Kobold', 'Kor', 'Merfolk', 'Metathran', 'Minotaur', 'Moonfolk', 'Noggle', 'Ogre',
    'Orc', 'Ouphe', 'Satyr', 'Siren', 'Slith', 'Soltari', 'Surrakar', 'Thalakos', 'Troll',
    'Vedalken', 'Werewolf', 'Yeti', 'Ainok', 'Amphin', 'Aven', 'Bearfolk', 'Cactusfolk',
    'Chordatans', 'Khenra', 'Kappa', 'Kitsune', 'Leonin', 'Loxodon', 'Nantuko', 'Kraul',
    'Naga', 'Nezumi', 'Orochi', 'Rakshasa', 'Raccoonfolk', 'Rhox', 'Saurids', 'Viashino',
    'Wolfir', 'Aetherborn', 'Angel', 'Archon', 'Avatar', 'Bringer', 'Demigod', 'Djinn',
    'Efreet', 'God', 'Inkling', 'Lamia', 'Nymph', 'Reflection', 'Shade', 'Shapeshifter',
    'Skeleton', 'Sliver', 'Specter', 'Spirit', 'Thrull', 'Vampire', 'Wraith', 'Zombie',
    'Beeble', 'Carrier', 'Demon', 'Devil', 'Dragon', 'Drone', 'Eldrazi', 'Elemental',
    'Eye', 'Glimmer', 'Gremlin', 'Harpy', 'Homarid', 'Homunculus', 'Horror', 'Illusion',
    'Imp', 'Incarnation', 'Kirin', 'Lammasu', 'Nephilim', 'Nightmare', 'Nightstalker',
    'Phyrexian', 'Spawn', 'Sphinx', 'Spirit', 'Thallid', 'Treefolk', 'Zubera',
    'Cephallid', 'Thallid', 'Sporoloth', 'Chimera', 'Mutant', 'Orgg', 'Volver', 'Weird',
    'Antelope', 'Ape', 'Armadillo', 'Aurochs', 'Badger', 'Bat', 'Bear', 'Beaver', 'Bird',
    'Boar', 'Camel', 'Capybara', 'Caribou', 'Cat', 'Coyote', 'Crab', 'Crocodile',
    'Dinosaur', 'Dog', 'Elephant', 'Elk', 'Ferret', 'Fish', 'Fox', 'Frog', 'Goat',
    'Hippo', 'Horse', 'Hyena', 'Insect', 'Jackal', 'Jellyfish', 'Leech', 'Lizard',
    'Llama', 'Mite', 'Mole', 'Mongoose', 'Monkey', 'Mouse', 'Nautilus', 'Octopus', 'Ox',
    'Oyster', 'Otter', 'Pangolin', 'Porcupine', 'Possum', 'Rabbit', 'Rat', 'Rhino',
    'Sable', 'Salamander', 'Scorpion', 'Shark', 'Sheep', 'Skunk', 'Sloth', 'Slug',
    'Snail', 'Snake', 'Spider', 'Sponge', 'Squid', 'Squirrel', 'Starfish', 'Trilobite',
    'Turtle', 'Weasel', 'Whale', 'Wolf', 'Wolverine', 'Wombat', 'Worm', 'Atog',
    'Basilisk', 'Beast', 'Brushwagg', 'Camarid', 'Cockatrice', 'Dragon', 'Drake',
    'Gargoyle', 'Griffin', 'Hellion', 'Hippogriff', 'Hydra', 'Kavu', 'Kraken',
    'Leviathan', 'Lhurgoyf', 'Licid', 'Manticore', 'Mutant', 'Pegasus', 'Pest',
    'Phelddagrif', 'Phoenix', 'Serpent', 'Slith', 'Sliver', 'Spike', 'Unicorn',
    'Varmint', 'Wurm', 'Fungi', 'Plant', 'Saproling', 'Splinter', 'Germ', 'Ooze',
    'Assembly-Worker', 'Blinkmoth', 'Chimera', 'Construct', 'Dreadnought', 'Gnome',
    'Golem', 'Juggernaut', 'Masticore', 'Myr', 'Pentavite', 'Pest', 'Prism', 'Robot',
    'Sculpture', 'Servo', 'Scarecrow', 'Tetravite', 'Thopter', 'Toy', 'Triskelavite',
    'Egg', 'Orb', 'Sand', 'Wall', 'Gith', 'Gnoll', 'Halfling', 'Tiefling', 'Beholder',
    'Hamster', 'Walrus', 'Astartes', 'Cyberman', 'Necron', 'Primarch', 'Synth',
    'Adipose', 'Ents', 'Hobbit', 'Judoon', 'Kaleds', 'Lupari', 'Menoptera', 'Silent',
    'Sontarans', 'Sycorax', 'Thijarians', 'Zyongs', 'C\'Tan', 'Maiar', 'Dalek', 'Tyranid',
    'Atraxi', 'Boekind',
];

export const multiWordRaces = [
    'Sea Devils', 'Ice Warriors', 'Time Lord', 'Weeping Angels'
];
